name: build

on:
  push:
    branches-ignore:
      - master
    tags:
      - '*'

jobs:
  Build:
    runs-on: [ self-hosted, vm ]
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: true
    outputs:
      version: ${{ steps.build_element.outputs.version }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Build Element
        id: build_element
        env:
          PUSH_CFG: ${{ secrets.PUSH_CFG }}
        run: |
          set -eux

          VERSION="$(exordos get-version .)"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

          exordos build $(pwd)

          # Decode and write the push configuration
          echo "$PUSH_CFG" | base64 -d > exordos/exordos.push.yaml
          exordos push -c exordos/exordos.push.yaml -t local -f --latest
  Test:
    needs: Build
    uses: exordos/exordos_ci/.github/workflows/element_realm_test.yml@master
    with:
      elements: metapaas
      version: ${{ needs.Build.outputs.version }}
      check-script: .github/scripts/check-metapaas.sh
    secrets: inherit
